name: Update Gatya TSV
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  update-tsv:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Vercel API
        run: |
          curl -s https://<あなたの-vercel-domain>/api/gatya
