name: Ping Vercel API

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -s https://rrolls.vercel.app/api/gatya
